//accounts
export const AUTH_REQUEST = "LOGIN";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SEND_CODE = "SEND_CODE";
export const VERIFY_CODE = "VERIFY_CODE";
export const CHANGE_EMAIL = "CHANGE_EMAIL";

//users
export const REGISTER_TEACHER = "REGISTER_TEACHER";
export const FIND_TEACHERS = "FIND_TEACHERS";
export const RESET_PASSWORD = "RESET_PASSWORD";

//disciplines
export const CREATE_DISCIPLINE = "CREATE_DISCIPLINE";
export const DELETE_DISCIPLINE = "DELETE_DISCIPLINE";
export const UPDATE_DISCIPLINE = "UPDATE_DISCIPLINE";
export const FIND_DISCIPLINES = "FIND_DISCIPLINES";
export const FIND_MY_DISCIPLINES = "FIND_MY_DISCIPLINES";
export const FIND_DISCIPLINE_BY_ID = "FIND_DISCIPLINE_BY_ID";
//exercises
export const FIND_ALL_EXERCISE_BY_DISCIPLINE_ID =
  "FIND_ALL_EXERCISE_BY_DISCIPLINE_ID";
export const FIND_EXERCISE_BY_ID = "FIND_EXERCISE_BY_ID";
export const CREATE_EXERCISE = "CREATE_EXERCISE";
export const UPDATE_EXERCISE = "UPDATE_EXERCISE";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
//files
export const GET_CONTENT_FILE = "GET_CONTENT_FILE";
export const FIND_EXERCISE_FILES = "FIND_EXERCISE_FILES";
export const CREATE_EXERCISE_FILE = "CREATE_EXERCISE_FILE";
export const DELETE_EXERCISE_FILE = "DELETE_EXERCISE_FILE";

//access-disciplines
export const REQUEST_DISCIPLINE_ACCESS = "REQUEST_DISCIPLINE_ACCESS";
export const ACCEPT_DISCIPLINE_ACCESS = "ACCEPT_DISCIPLINE_ACCESS";
export const REJECT_DISCIPLINE_ACCESS = "REJECT_DISCIPLINE_ACCESS";
export const GET_ALL_DISCIPLINE_ACCESS = "GET_ALL_DISCIPLINE_ACCESS";
