# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy best-edu-web

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies.
      run: npm ci
    - name: Build project.
      run: npm run build --if-present
    - name: Transfer dist/* to /var/www/.
      run: mv dist/* /var/www/best-edu-web/html/
